name: Build Irssi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          meson ninja-build \
          build-essential \
          autoconf automake libtool \
          pkg-config libglib2.0-dev \
          libssl-dev libperl-dev \
          libncurses5-dev libncursesw5-dev

    - name: Configure with meson
      run: |
        meson Build

    - name: Build with ninja
      run: |
        ninja -C Build

